<?php

/**
 * @file
 * Contains workshops.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function workshops_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the workshops module.
    case 'help.page.workshops':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RC Workshop Formatter') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function workshops_theme() {
  return [
    'workshops' => [
      'render element' => 'children',
    ],
  ];
}
